### ISSUE TITLE
Sort by publication Date

### ISSUE THREAD

**Issue by MAbuain17** [ken0225/RIS-Codes-Collection#10]
Hi, nice work gathering this collection!
could you make maybe an excel spreadsheet sorting the codes by date of which the papers are published?
thanks!

**Comment by ken0225** [comment]
Hi MAbuain17!

I am delighted that this project has been beneficial to you, and I appreciate your suggestion. Sorting the codes by date is indeed a great idea, so I will incorporate this feature in the next version.

Best regards,

Ken
