### ISSUE TITLE
The Rumble in the Millimeter Wave Jungle: Obstructions Vs RIS

### ISSUE THREAD

**Issue by JuanMarcosRamirez** [ken0225/RIS-Codes-Collection#13]
https://github.com/JuanMarcosRamirez/outage_RIS_indoor

Juan Marcos Ramirez

22st Mediterranean Communication and Computer Networking Conference (MedComNet 2024)

**Comment by ken0225** [comment]
Dear Juan Marcos Ramirez,

Many thanks for providing the information to this project. Your code has already been added to the list.

Best regards,

Ken
