### ISSUE TITLE
New Code for Beamforming Optimization with RIS (Unsupervised Learning)

### ISSUE THREAD

**Issue by khinthandarkyaw98** [ken0225/RIS-Codes-Collection#14]
Hello, thank you for your code collection.

I would like to request you add my repo to your code collection.

paper: https://ieeexplore.ieee.org/document/10595028
code: https://github.com/khinthandarkyaw98/BF-RIS-Channel-Covariance-DeepLearning

**Comment by ken0225** [comment]
hi, I have already added you nice work :)

best regards~

Ken
