### ISSUE TITLE
RIS Codes from Connectivity Section, Aalborg University

### ISSUE THREAD

**Issue by victorkreutzfeldt** [ken0225/RIS-Codes-Collection#15]
Hi Ke Wang,

I am grateful for your initiative and I think it is a very important mindset to bring up the open science premises to the wireless communications industry, which is already seen as a natural feature in other communities such as machine learning. 

We, from the Connectivity Section (AAU) under the supervision of Dr. Petar Popovski, also believe in this and make our contributions available; examples:

https://github.com/victorcroisfelt/self-configuring-orchestration
https://github.com/victorcroisfelt/ris-random-access-channel-oracle
https://github.com/lostinafro/ris-control
https://github.com/victorcroisfelt/a-random-access-protocol-ris-assisted
https://github.com/victorcroisfelt/mec-with-ris-control

Best regards,
Victor Croisfelt

**Comment by ken0225** [comment]
Hi Victor!

I'm very pleased that you provided this important information for your publications and related codes. Thank you very much for reminding me of this.

I have already added your codes to the project, please check Nos. 157-161. I believe these papers and codes will benefit the community. Besides, I also want to express my thanks to Prof. Petar Popovski with the highest regards.

Best regards,

Ken
