### ISSUE TITLE
New codes about RIS

### ISSUE THREAD

**Issue by AhmadSirojuddin** [ken0225/RIS-Codes-Collection#16]
Hi. 
You may consider to add codes that relate to two of my publications at IEEE Wireless Communications Letters

https://github.com/AhmadSirojuddin/Low-Complexity-Sum-Capacity-Maximization-for-Intelligent-Reflecting-Surface-Aided-MIMO-Systems

https://github.com/AhmadSirojuddin/MIMO-Capacity-Maximization-With-a-Practical-Model-for-Reconfigurable-Intelligent-Surfaces

**Comment by ken0225** [comment]
Dear Ahmad Sirojuddin,

Your codes have already been integrated into the project, please check Nos. 165&166.

Many thanks for your support!

Best regards

Ken
