### ISSUE TITLE
Joint Spectrum, Precoding, and Phase Shifts Design for RIS-Aided Multiuser MIMO THz Systems

### ISSUE THREAD

**Issue by mahdimathematics** [ken0225/RIS-Codes-Collection#18]
Hi @ken0225,
Our new paper is recently accepted to IEEE TCOM.
Here is the link for the paper and code.
https://ieeexplore.ieee.org/abstract/document/10472941
https://github.com/Ali-Meh619/MHGphormer

I appreciate it if you can include that in your github account.

Thanks,
Ali

**Comment by ken0225** [comment]
Hi Ali Mehrabian,

Congratulations on your acceptance by TCOM! Your code has already been included. Please check it at your convenience.

Best regards,

Ken
