### ISSUE TITLE
Robust Design for Intelligent Reflecting Surface Assisted MIMO-OFDMA Terahertz IoT Networks

### ISSUE THREAD

**Issue by Kimiahak** [ken0225/RIS-Codes-Collection#8]
Hi there,
good day to you
this is kimia .
Thanks for your great collection, it is so useful and actually it is helping me to understand and learn how to program the IRS with it. Right now I am working on this paper which is : Robust Design for Intelligent Reflecting Surface Assisted MIMO-OFDMA Terahertz IoT Networks.

This is also something new and so practical, right now people are working on it at Surrey university. Can you please kindly check it and see if you can get the codes or any hint on how I can start simulating this paper ?
it would be so great to hear from you you can send me email at kimiahak98@gmail.com
[Robust Design for Intelligent Reflecting Surface.pdf](https://github.com/ken0225/RIS-Codes-Collection/files/12138769/Robust.Design.for.Intelligent.Reflecting.Surface.pdf)

**Comment by ken0225** [comment]
hi, i will let you know if the required code is found, thanks.

**Comment by Kimiahak** [comment]
Hi again dear ken,
many many thanks for your kind help and attention.
I saw you closed this as completed. Since I am new here just wanted to ask if you have find the code or is it just something in github ?! 
again thanks a lot for your attention
