### ISSUE TITLE
Submodular Optimization for Placement of Intelligent Reflecting Surfaces in  sensing systems

### ISSUE THREAD

**Issue by TaraEsmaeilbeig** [ken0225/RIS-Codes-Collection#9]
The codes for the 2023 IEEE CAMSAP article "Submodular Optimization for Placement of Intelligent Reflecting Surfaces in  sensing systems" is provided [here](https://github.com/TaraEsmaeilbeig/Submodular-Optimization). 
please  refer to our work below if you use the code:

@article{esmaeilbeig2023submodular,
  title={Submodular Optimization for Placement of Intelligent Reflecting Surfaces in Sensing Systems},
  author={Esmaeilbeig, Zahra and Vijay Mishra, Kumar and Eamaz, Arian and Soltanalian, Mojtaba},
  journal={arXiv e-prints},
  pages={arXiv--2310},
  year={2023}
}

**Comment by ken0225** [comment]
hi tara!

very happy to know your paper & related code, it will be contained in the project soon.

please see the update information.

Best regards

Ken
